version: 2

formats: []

sphinx:
  builder: html
  configuration: docs/source/conf.py

build:
    image: latest

python:
  version: "3.8"
  install:
    - method: pip
      path: .

    # inspired by: https://github.com/pyg-team/pytorch_geometric/blob/master/docs/requirements.txt
    - requirements: docs/requirements.txt
  system_packages: true
